### ISSUE TITLE
A few suggestions/issues noted

### ISSUE THREAD

**Issue by Penetrosity** [floowsnaake/RPG-MO---All-in-one-Bot#2]
Have found that alttabbing doesn't force it to check and make sure it was in the window, it's a good idea to kill the program as soon as alttab so it doesn't do hijinks in other windows
I believe you would be looking for something along the lines of
ifWinNotActive, RPG MO
Reload
or pause, after most functions, there is probably a better way to do it in AHK I am willing to find out if you're unsure.

I'm not sure how it is you pull up the info on full inventory I haven't finished looking through the code carefully and mainly skimmed over it. A few things I've noticed is that at the start it doesn't check inventory full or not just goes back to stash, sometimes does some weird stash things because of the 'clicking' and sometimes pulls some things out ofstash and puts them back in.

Default walkspeed is a bit slow, having options like in Papa Digger was much nicer it looks like.

When it goes back for the second set at least for fishing, it never seems to go back to the stash unless I click start bot again. I noticed this for the built in sandbot as well.

It seems sometimes if it does decide to go back if the bot was currently doing an action (Fishing, digging, etc) it eats some of the steps and causes the whole thing to fail and your bot to end up in the wrong place entirely.

I haven't touched AHK in a while but I'll try to fix some of these issues on my own if possible.

**Comment by Penetrosity** [comment]
Ah another thing to add here, it seems that sometimes even if you add the movement into the tile to do work on into the movement script it won't start it.The chest will also always do the click even if you added the movement into it, I might just be missing something from the guide.

**Comment by aberrau** [comment]
I have noticed the same issues:
- It never goes back to stash unless you hit start. It seams to get stuck at "Working..." step
- It ignores pet inventory, no matter which option you check (No pet, 4, 8, 12, 16)
