### ISSUE TITLE
flowsnake are you still up for botting?

### ISSUE THREAD

**Issue by BubonicPestilence** [floowsnaake/RPG-MO---All-in-one-Bot#3]
flowsnake are you still up for botting?

I'm currently got banned for my own off-game bot, which works as normal game client.
What i already done with my bot:
- all resource farming w/ destroying them
- sand mining w/ delivery to chest

If you're interested to join my project, feel free to contact me.

Oh, and captcha not a problem.

And it's written in Ruby :)

**Comment by manawe** [comment]
Hey there,

I would be interested to help out where I can. 
I am not very experienced in coding, but I do have a lot of experience with the game, which might help out. Recently my main finally got banned after 200+ days of playing, so I guess I wouldn't mind being involved in a new project.

Kind regards,

Manawe

**Comment by RStudios** [comment]
_grabs popcorn_

**Comment by BubonicPestilence** [comment]
Don't worry, i'll release it as full package :)

**Comment by RStudios** [comment]
Well it cant be any more amateur than this one

**Comment by BubonicPestilence** [comment]
Hm... yeah, but still good pathfinding, goap and bt help me build some starting pointing just from dorpat :)

**Comment by BubonicPestilence** [comment]
```
 INFO  MOE::CHAT : [EN] rstudios: joe they wont talk in there for long :D
 INFO  MOE::CHAT : [E9] rstudios: whos incharge here now?
 INFO  MOE::CHAT : [E9] rstudios: not you
```

/me eating popcorn while botting & rstudios chatting 🌽

**Comment by floowsnaake** [comment]
haha i love popcorn
